development:
  YELP_WSID: "tQd1EAsNyd6Pmdmt653HzA"
  YELP_KEY: "fY6wOVe4OKHPb8FE_9Idmg"
  YELP_SECRET: "WXO7X8_eQvCEIYv28HPQhgkSZ2E"
  YELP_TOKEN: "slDSKW_7qjDqMl2YiCEGNAVD7Bn35fgS"
  YELP_TOKEN_SECRET: "eT9hoFWiTt52_HoYrQzi-jwT_ZY"
  GOOGLE_KEY: "726538167691.apps.googleusercontent.com"
  GOOGLE_SECRET: "wswPORTm-zwnLWBeEI_CJxur"
  GOOGLE_PLACES: "AIzaSyDfQUGytBit3OsfLDx8OygAllI9SJnXaIM"
  FACEBOOK_KEY: "184874611662697"
  FACEBOOK_SECRET: "6556eb96ca575ece887bc64988d8ce4c"

  TWITTER_KEY: "ImqXx02e2k9s32ZD1Ym13A"
  TWITTER_SECRET: "qnOyZuhl2xeIxuR2ubc3v0udUo3Hp8kXrHYXGpzE"